/**
 * JiUI - Declarative UI Framework for C/C++
 * Copyright (c) 2026 Ali A Alwahed (https://github.com/Ali-A-2026)
 *                    Hyder61112
 * Licensed under the GNU Lesser General Public License v3.0 (LGPL-3.0)
 *
 * @file jiui.h
 * @brief Umbrella header — include this for the complete JiUI C API.
 */

#ifndef JIUI_H
#define JIUI_H

/* Configuration (generated by CMake) */
#include <jiui/ji_config.h>

/* Fundamental macros & platform detection */
#include "ji_defines.h"

/* Dynamic linking export macros */
#include "ji_api.h"

/* Core geometric types */
#include "ji_types.h"

/* Memory management & reference counting */
#include "ji_memory.h"

/* Error handling & logging */
#include "ji_error.h"

/* Runtime type system */
#include "ji_type.h"

/* Property system */
#include "ji_property.h"

/* Object base class */
#include "ji_object.h"

/* .ji file lexer (legacy curly-brace format) */
#include "ji_lexer.h"

/* .ji file XML lexer */
#include "ji_xml_lexer.h"

/* .ji file AST nodes */
#include "ji_ast.h"

/* .ji file parser (legacy curly-brace format) */
#include "ji_parser.h"

/* .ji file XML parser */
#include "ji_xml_parser.h"

/* Tree builder — AST → JiObject tree */
#include "ji_tree_builder.h"

/* Resource dictionary */
#include "ji_resource.h"

/* Binding engine */
#include "ji_binding.h"

/* Event handler system */
#include "ji_event.h"

/* Runtime .ji file loader */
#include "ji_loader.h"

/* AOT code generator */
#include "ji_codegen.h"

/* Layout system */
#include "ji_layout.h"

/* Panel types */
#include "ji_panel.h"

/* Visual system */
#include "ji_visual.h"

/* Drawing primitives */
#include "ji_drawing.h"

/* Control base class */
#include "ji_control.h"

/* Core widgets */
#include "ji_widgets.h"

/* Styling & theming */
#include "ji_style.h"

/* Qt6-style color palette & theme engine */
#include "ji_palette.h"

/* GPU backend abstraction (Vulkan, OpenGL, Software) */
#include "ji_gpu.h"

/* Scene graph for hardware-accelerated rendering */
#include "ji_scene.h"
#include "ji_compositor.h"
#include "ji_gpu_effects.h"
#include "ji_frame_graph.h"
#include "ji_font.h"
#include "ji_text_engine.h"
#include "ji_svg.h"
#include "ji_constraint.h"
#include "ji_gesture.h"
#include "ji_input.h"
#include "ji_jiml.h"
#include "ji_hot_reload.h"
#include "ji_dock_pro.h"
#include "ji_3d.h"
#include "ji_material.h"
#include "ji_physics.h"
#include "ji_neural.h"

/* Phase 8: Developer Tools & Plugins */
#include "ji_profiler.h"
#include "ji_plugin.h"
#include "ji_automation.h"
#include "ji_builder.h"

/* Phase 9: i18n & Accessibility */
#include "ji_i18n.h"
#include "ji_accessibility.h"
#include "ji_hidpi.h"
#include "ji_sandbox.h"

/* Phase 10: Multi-threading, Multimedia & Testing */
#include "ji_threads.h"
#include "ji_multimedia.h"
#include "ji_screenshot_test.h"

/* Qt6 Fusion style renderer */
#include "ji_qt_style.h"

/* Docking system */
#include "ji_dock_widget.h"
#include "ji_dock_area.h"
#include "ji_dock_manager.h"
#include "ji_splitter.h"
#include "ji_dock_overlay.h"
#include "ji_dock_tab_bar.h"
#include "ji_dock_serializer.h"

/* Container widgets */
#include "ji_group_box.h"
#include "ji_frame.h"
#include "ji_scroll_area.h"
#include "ji_tab_widget.h"
#include "ji_stacked_widget.h"
#include "ji_tool_bar.h"
#include "ji_status_bar.h"
#include "ji_menu.h"

/* Input widgets */
#include "ji_radio_button.h"
#include "ji_spin_box.h"
#include "ji_double_spin_box.h"
#include "ji_combo_box.h"
#include "ji_text_edit.h"
#include "ji_plain_text_edit.h"
#include "ji_date_time_edit.h"
#include "ji_dial.h"
#include "ji_scroll_bar.h"

/* Button widgets */
#include "ji_tool_button.h"
#include "ji_command_link_button.h"

/* Layout widgets */
#include "ji_box_layout.h"
#include "ji_form_layout.h"
#include "ji_flow_layout.h"

/* Advanced widgets */
#include "ji_model_view.h"

/* Animation framework */
#include "ji_animation.h"

/* Undo/Redo framework */
#include "ji_undo_stack.h"

/* Graphics effects */
#include "ji_effects.h"

/* Stylesheet engine */
#include "ji_stylesheet.h"

/* Platform backends */
#include "ji_platform.h"

/* Window abstraction */
#include "ji_window.h"

/* --------------------------------------------------------------------------
 * Library initialization / shutdown
 * -------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Initialize the JiUI library.
 * Must be called before any other JiUI function.
 * @return JI_OK on success, error code on failure.
 */
JI_API JiResultCode ji_initialize(void);

/**
 * Shut down the JiUI library and release all global resources.
 * Must be called exactly once before process exit.
 */
JI_API void ji_shutdown(void);

/**
 * Get the library version string (e.g. "1.0.0").
 */
JI_API const char* ji_version(void);

#ifdef __cplusplus
}
#endif

#endif /* JIUI_H */
