#if !defined(_POSIX_C_SOURCE)
#define _POSIX_C_SOURCE 200809L
#endif

/**
 * JiUI - Declarative UI Framework for C/C++
 * Copyright (c) 2026 Ali A Alwahed (https://github.com/Ali-A-2026)
 *                    Hyder61112
 * Licensed under the GNU Lesser General Public License v3.0 (LGPL-3.0)
 *
 * @file ji_builder_codegen.c
 * @brief Code generation from builder design — C, C++, and JiML output.
 */

#include "jiui/ji_builder.h"
#include <string.h>
#include <stdio.h>

/* =========================================================================
 * C Code Generation
 * ========================================================================= */

static int gen_c_widget(const JiBuilderWidget* w, int depth, char* buf, int buf_size)
{
    int written = 0;
    char indent[64];
    for (int i = 0; i < depth && i < 32; i++) indent[i] = ' ';
    indent[depth] = '\0';

    const char* type_name = ji_builder_widget_type_name(w->type);

    written += snprintf(buf + written, (size_t)(buf_size - written),
        "%s/* %s (id=%d) */\n", indent, w->name, w->id);
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "%sJiWidget* %s = ji_widget_new(JI_WIDGET_%s);\n",
        indent, w->name, type_name);
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "%sji_widget_set_bounds(%s, %.0f, %.0f, %.0f, %.0f);\n",
        indent, w->name,
        w->bounds.x, w->bounds.y, w->bounds.width, w->bounds.height);

    /* Properties */
    for (int i = 0; i < w->prop_count && written < buf_size - 1; i++) {
        written += snprintf(buf + written, (size_t)(buf_size - written),
            "%sji_widget_set_property(%s, \"%s\", \"%s\");\n",
            indent, w->name, w->properties[i].key, w->properties[i].value);
    }

    return written;
}

int ji_builder_gen_c(const JiBuilder* builder, char* buf, int buf_size)
{
    if (!builder || !buf || buf_size <= 0) return 0;
    int written = 0;

    written += snprintf(buf + written, (size_t)(buf_size - written),
        "/* Generated by JiUI Visual Builder */\n");
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "#include <jiui/jiui.h>\n\n");

    /* Generate root-level widgets (parent_id == -1) */
    for (int i = 0; i < builder->widget_count && written < buf_size - 1; i++) {
        if (builder->widgets[i].parent_id == -1) {
            written += gen_c_widget(&builder->widgets[i], 0,
                                      buf + written, buf_size - written);
        }
    }

    /* Generate child widgets */
    for (int i = 0; i < builder->widget_count && written < buf_size - 1; i++) {
        if (builder->widgets[i].parent_id != -1) {
            written += gen_c_widget(&builder->widgets[i], 1,
                                      buf + written, buf_size - written);
        }
    }

    return written;
}

/* =========================================================================
 * C++ Code Generation
 * ========================================================================= */

int ji_builder_gen_cpp(const JiBuilder* builder, char* buf, int buf_size)
{
    if (!builder || !buf || buf_size <= 0) return 0;
    int written = 0;

    written += snprintf(buf + written, (size_t)(buf_size - written),
        "// Generated by JiUI Visual Builder\n");
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "#include <jiui/jiui.hpp>\n\n");

    for (int i = 0; i < builder->widget_count && written < buf_size - 1; i++) {
        const JiBuilderWidget* w = &builder->widgets[i];
        const char* type_name = ji_builder_widget_type_name(w->type);
        written += snprintf(buf + written, (size_t)(buf_size - written),
            "auto %s = Ji::Widget::create(Ji::WidgetType::%s);\n",
            w->name, type_name);
        written += snprintf(buf + written, (size_t)(buf_size - written),
            "%s->setBounds({%.0f, %.0f, %.0f, %.0f});\n",
            w->name, w->bounds.x, w->bounds.y, w->bounds.width, w->bounds.height);

        for (int j = 0; j < w->prop_count && written < buf_size - 1; j++) {
            written += snprintf(buf + written, (size_t)(buf_size - written),
                "%s->setProperty(\"%s\", \"%s\");\n",
                w->name, w->properties[j].key, w->properties[j].value);
        }
        written += snprintf(buf + written, (size_t)(buf_size - written), "\n");
    }

    return written;
}

/* =========================================================================
 * JiML Code Generation
 * ========================================================================= */

static const char* jiml_tag_for_type(JiBuilderWidgetType type)
{
    switch (type) {
        case JI_BW_WINDOW:      return "JiWindow";
        case JI_BW_BUTTON:      return "JiButton";
        case JI_BW_LABEL:       return "JiLabel";
        case JI_BW_TEXT_EDIT:   return "JiTextEdit";
        case JI_BW_CHECKBOX:    return "JiCheckBox";
        case JI_BW_RADIO:       return "JiRadioButton";
        case JI_BW_COMBO:       return "JiComboBox";
        case JI_BW_LIST:        return "JiListView";
        case JI_BW_TREE:        return "JiTreeView";
        case JI_BW_TABLE:       return "JiTableView";
        case JI_BW_TAB_WIDGET:  return "JiTabWidget";
        case JI_BW_SCROLL_AREA: return "JiScrollArea";
        case JI_BW_SPLITTER:    return "JiSplitter";
        case JI_BW_TOOLBAR:     return "JiToolBar";
        case JI_BW_MENUBAR:     return "JiMenuBar";
        case JI_BW_STATUSBAR:   return "JiStatusBar";
        case JI_BW_FRAME:       return "JiFrame";
        case JI_BW_DIAL:        return "JiDial";
        case JI_BW_SLIDER:      return "JiSlider";
        case JI_BW_SPINBOX:     return "JiSpinBox";
        case JI_BW_CANVAS:      return "JiCanvas";
        case JI_BW_VIEWPORT_3D: return "Ji3DViewport";
        default:                return "JiWidget";
    }
}

static int gen_jiml_widget(const JiBuilder* b, int widget_id, int depth,
                            char* buf, int buf_size)
{
    int written = 0;
    char indent[64];
    for (int i = 0; i < depth * 2 && i < 62; i++) indent[i] = ' ';
    indent[depth * 2] = '\0';

    /* Find widget */
    const JiBuilderWidget* w = NULL;
    for (int i = 0; i < b->widget_count; i++) {
        if (b->widgets[i].id == widget_id) { w = &b->widgets[i]; break; }
    }
    if (!w) return 0;

    const char* tag = jiml_tag_for_type(w->type);

    /* Open tag with attributes */
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "%s<%s name=\"%s\" x=\"%.0f\" y=\"%.0f\" width=\"%.0f\" height=\"%.0f\"",
        indent, tag, w->name,
        w->bounds.x, w->bounds.y, w->bounds.width, w->bounds.height);

    /* Properties as attributes */
    for (int i = 0; i < w->prop_count && written < buf_size - 1; i++) {
        written += snprintf(buf + written, (size_t)(buf_size - written),
            " %s=\"%s\"", w->properties[i].key, w->properties[i].value);
    }

    /* Check for children */
    bool has_children = false;
    for (int i = 0; i < b->widget_count; i++) {
        if (b->widgets[i].parent_id == widget_id) {
            has_children = true;
            break;
        }
    }

    if (!has_children) {
        written += snprintf(buf + written, (size_t)(buf_size - written), "/>\n");
    } else {
        written += snprintf(buf + written, (size_t)(buf_size - written), ">\n");
        /* Generate children */
        for (int i = 0; i < b->widget_count && written < buf_size - 1; i++) {
            if (b->widgets[i].parent_id == widget_id) {
                written += gen_jiml_widget(b, b->widgets[i].id, depth + 1,
                                            buf + written, buf_size - written);
            }
        }
        written += snprintf(buf + written, (size_t)(buf_size - written),
            "%s</%s>\n", indent, tag);
    }

    return written;
}

int ji_builder_gen_jiml(const JiBuilder* builder, char* buf, int buf_size)
{
    if (!builder || !buf || buf_size <= 0) return 0;
    int written = 0;
    written += snprintf(buf + written, (size_t)(buf_size - written),
        "<!-- Generated by JiUI Visual Builder -->\n");

    /* Generate root-level widgets */
    for (int i = 0; i < builder->widget_count && written < buf_size - 1; i++) {
        if (builder->widgets[i].parent_id == -1) {
            written += gen_jiml_widget(builder, builder->widgets[i].id, 0,
                                        buf + written, buf_size - written);
        }
    }

    return written;
}
